### ISSUE TITLE
bug extraño en mi calendario

### ISSUE THREAD

**Issue by Nitrilo** [steelwow/Bugtracker-434#103]
Buenas, me explico claro y concreto, mi pj llamado Grignard esta presentado un bug extraño en su calendario de actividades, el cual como verán en la imagen que adjunto,
http://gyazo.com/d58a673f0ae70fd01cc7638f62b741fe
http://gyazo.com/0e27c228b7fc7f5eb9cfcff5a74c5cf0
http://gyazo.com/bd8b6955a18f552d9609339047b6c08a (en esta ultima observaran la locura que a tomado el calendario)
muestra actividades de diversas que se yo! mazmorras como si las hubiera realizado, y claro esta que no! porque como ven me muestra reporte en todas las fechas del mes y de los sigtes, claro estos se van quitando a medida que pasan los días pero es la misma broma porque sigue ahí el problema.. La situación es que por lo menos a la hora de querer hacer un simple baradin no recuerdo si me toca o no! porque me muestra reporte en todas las fechas, es medio incomodo esto por esa razon, el no saber cuando se me reinician las estancias que realizo, menciono algo mas, esto comenzó justo después de haber terminado un baradin el cual al líder se le había bugeado el lot y fuimos atendido inmediatamente por un GM (no recuerdo su nombre) y luego note esta locura..

por ultimo me excuso si es o no! el sitio donde debí reportar el bug pero esta web es primera vez que la manejo y ni idea donde se postean los nuevos reportes..

aqui otra muestras
![wowscrnshot_012815_003207](https://cloud.githubusercontent.com/assets/10735990/5932759/59e66358-a686-11e4-8e27-5379832abdda.jpg)

**Comment by ghost** [comment]
En el calendario, apartado filtros, quita el tick de reinicios de banda...

**Comment by Nitrilo** [comment]
muchas gracias..

**Comment by GmTemis** [comment]
No corresponden este tipo de daños individuales, este espacio es para reportes en general. En una futura ocasión utiliza el foro
