### ISSUE TITLE
Bug Spell: Sed de Sangre guerrero Furia

### ISSUE THREAD

**Issue by wlesempai** [steelwow/Bugtracker-434#108]
He visto que en las ultimas almas en las que eh ido los bosses se curan pero eso no es un bug de los bosses, testando descubrimos juntos con un amigo que los bosses se curan por la habilidad sed de sangre de los guerreros furia, También cuando rematas mobs con Sen de sangre los mobs no se mueren se quedan a 1 punto de vida y se quedan parados sin hacer nada.
 Atentamente Plagadins

**Comment by rodrigoalv** [comment]
se ha reparado
