### ISSUE TITLE
Spell: Pestilencia - Death Knight

### ISSUE THREAD

**Issue by ciroagc** [steelwow/Bugtracker-434#109]
Básicamente la spell no hace nada. Debería repartir las diseases que tiene el target en los mobs cercanos, pero no ocurre. Es fundamental a la hora de tanquear como dpsear, especialmente para los DK Unholy (profano).
Actualmente solo gasta la runa, se ve el efecto visual de esparcimiento, pero no pasa nada más.

**Comment by rodrigoalv** [comment]
Se ha reparado, cuando se reinicie el servidor estara disponible.
