### ISSUE TITLE
[NPC] - Falta de NPC en Valle de la Sabiduría (Orgrimmar)

### ISSUE THREAD

**Issue by Convive** [steelwow/Bugtracker-434#117]
Este NPC no se encuentra en el juego: http://www.wowhead.com/npc=3322/kaja
Debería estar al lado del yunque de Opuno: http://www.wowhead.com/npc=44781/opuno-ironhorn

Espero puedan resolverlo.

Saludos.

**Comment by GmTemis** [comment]
Solucionado
