### ISSUE TITLE
Cadena de misiones el protodraco verde BUG

### ISSUE THREAD

**Issue by Punxa** [steelwow/Bugtracker-434#118]
Hola buenas al empezar la cadena de misiones en el lago para el protodraco verde, al hacer todas ya no me dan mas misiones y reputación con los ( los oráculos ) me tendrían que dar diarias en la cueva pero tampoco me dan aqui les dejo  el link del huevo. espero que lo arreglen llevo diciendolo desde dreamwow 
http://www.wowhead.com/item=39878/mysterious-egg 
un saludo.

**Comment by GmTemis** [comment]
Hola, el reporte ya esta en lista de espera, gracias por reportarlo.
