### ISSUE TITLE
[Item] Nido del ultimo dragon. REPOST

### ISSUE THREAD

**Issue by Melenaris** [steelwow/Bugtracker-434#127]
Descripcion: Cuando infliges daño tienes una probabilidad de obtener 2904 p. de golpe crítico durante 20 s.

Problema: El respectivo abalorio carece de Cooldown/CD (Enfriamiento) interno, Es decir se activa practicamente en todo momento.Ademas que no solo se activa cuando el usuario del abalorio inflige daño sino que tambien cuando le infligen daño al jugador

.Esto no solo sucede con este abalorio sino tambien con todos los abalorios de Alma de Dragon, los cuales sus efectos se basan en probabilidades como medio de activacion.

Aqui dejo el link de wowhead: http://es.wowhead.com/item=77972

**Comment by Melenaris** [comment]
Aca dejo los links de todos los reportes de este abalorio que desbalancea el pvp tan asquerosamente. De los cuales el primero ya fue reportado hace mas de 1 mes por mi persona y el segundo hace 23 dias.

https://github.com/steelwow/Bugtracker-434/issues/44

https://github.com/steelwow/Bugtracker-434/issues/88

Ahora pregunto, durante cuanto tiempo mas tenemos que ser follados por gente que se aprobecha de este abuso para que pase a ser 1 prioridad de arreglo? Porque la verdad que te venga follando toda la puta comunidad durante 1 mes sin ningun tipo de respuesta del staff creo que esta cansando a mas de 1.

**Comment by GmTemis** [comment]
Reparado
