### ISSUE TITLE
Perdida de objetos subastados

### ISSUE THREAD

**Issue by smiedth** [steelwow/Bugtracker-434#131]
subaste con mi pnj Catabum y Cataclysmico +de 100 objetos 15 horas después al revisar mi subasta muchos objetos entre ellos mis viales de arenas, aparecían 2 segundos y luego iban desapareciendo
1 por 1 y al revisar Consulta de subastas  aparecían solo algunos de estos objetos desaparecidos pero al hacerles clic desaparecían, luego entre a mi pnj Cataclismo y pasaba lo mismo;  entre las subastas desaparecidas estaban  Elementium Endurecido, entonces subaste mas de esto y me salio (ERROR INTERNO DE SUBASTAS) no me dejaba subastar mas de esto; 7 horas después ya estaban desaparecidos completamente  y ya no me salia el error interno de subastas; yo solo quiero mis 2 viales de arenas que invertí 52k en hacerlas el resto no me interesa que se pierdan por favor

yo hago viales miren:
![viales](https://cloud.githubusercontent.com/assets/8040397/6179436/4005ea18-b2e7-11e4-957d-4ccf03f27925.jpg)

soy de subastar bastantes objetos y me enterado que hay otros que les pasa lo mismo pero la perdida no es tan grande

**Comment by smiedth** [comment]
miren sale esto ; error interno de subastas 
![error](https://cloud.githubusercontent.com/assets/8040397/6198663/1e544d4e-b3df-11e4-99f7-3de1a0b9eada.jpg)

1x1 me deja, pero subastar x montones sale error

**Comment by GmTemis** [comment]
Este reporte debe ir en los foros del servidor.
