### ISSUE TITLE
caparazon antimagia bug dk

### ISSUE THREAD

**Issue by akonet** [steelwow/Bugtracker-434#133]
http://es.wowhead.com/spell=48707/caparazon-antimagia cuando lo tiene activado evita que se le pueda dar cc y ese no es su cometido puesto qe el stun o cc no hace daño y solo deberia evitar los hechizos dañinos.

**Comment by rodrigoalv** [comment]
Segun lo encontrado por blizard, da inmunidad a cualquier efecto magico dañino o no.

Saludos
