### ISSUE TITLE
SUPERVIVENCIA CAZADOR

### ISSUE THREAD

**Issue by sabix** [steelwow/Bugtracker-434#150]
los skill de la rama de supervivencia del cazador su daño esta muy por debajo del normal... supervivenvia deberia ser mucho mejor en daño que punteria solo con disparo explosivo y flecha negra pero su daño por segundo es damaciado bajo 700p eso es lo que baja flecha negra y disparo de explosion 1k... acomoden esa rama ... su daño es muy bajo hasta un lvl 85 sañoso lo vence O.o

**Comment by rodrigoalv** [comment]
mal reporte se cierra por no cumplir los requerimientos
