### ISSUE TITLE
Bug tier 13 paladin

### ISSUE THREAD

**Issue by LEAL18** [steelwow/Bugtracker-434#152]
Hace rato que esta bug,el bonus dice claramente que sentencia genera 1 carga de poder sagrado
http://subefotos.com/ver/?5cabe356198b7d450b1859802a90ecd3o.jpg
Pero,en su lugar,cada golpe de cruzado se genera 2 cargas de poder
http://subefotos.com/ver/?52cac91de0f1de7f8212cef3c17a2c9eo.jpg
http://subefotos.com/ver/?84b13c5d17df627e5f7f01278d558976o.jpg
mas sentencia serian las 3
http://subefotos.com/ver/?48fe44a783724e83fe1a68f0132089c3o.jpg
y usando tormenta divina se generan las 3 de una sola vez al golpear a 2 jugadores
http://subefotos.com/ver/?4e2c2e5d38ba1307248714f24d3a573ao.jpg
http://subefotos.com/ver/?d789523b97b932e4106fbcef83f1cafdo.jpg
consagración genera todo el tiempo que este el enemigo sobre el area
http://subefotos.com/ver/?6248b17229e5f2c7e07fd9894ca54ca2o.jpg
http://subefotos.com/ver/?016725488232ade14797ff079275bce4o.jpg
Creo que deberían darle una solución urgente,ya que hay mucha gente que cambia el rumbo de una bg al pegar tanto y muy seguido...además,el paladin es una clase de SOPORTE.

**Comment by rodrigoalv** [comment]
Hola, se ha reparado! perdon la demora
