### ISSUE TITLE
Bug  "C.I." Abalorios Vórtice transfigurador de Almas, Insignia de mente corrupta y Sello de los 7 simbolos

### ISSUE THREAD

**Issue by Jualk** [steelwow/Bugtracker-434#154]
Leyendo foros sobre estos 3 abalorios y revisando el changelog del server, observo que hay un error en los Coldown internos (CI) de estos abalorios que según el changelog del server:

-INSIGNICA DE MENTE CORRUPTA(buscador, normal, heroico): tiene 25 segundos de cooldown interno y 15% de probabilidad de lanzarlo..
-VORTICE TRANSFIGURADOR DE ALMAS(buscador, normal, heroico): tiene 25 segundos de cooldown interno y 15% de probabilidad de lanzarlo.
-SELLO DE LOS SIETE SIMBOLOS (buscador, normal, heroico): tiene 25 segundos de cooldown interno y 15% de probabilidad de lanzarlo.

Basandome en lo leido en el foro:
http://es.wowhead.com/item=77991/insignia-de-mente-corrupta#english-comments http://es.wowhead.com/item=77990/vortice-transfigurador-de-almas#english-comments
http://es.wowhead.com/item=77969/sello-de-los-siete-simbolos#english-comments
Los CI Insignia de mente corrupta 115 seg. con 15% prob. lanzarlo, vortice transfigurador de alma 1min :45 seg con 15% de prob. lanzamiento y sello de los 7 simbolos de 2 minutos con 15% de prob. lanzamiento; son iguales o parecidos al arreglo del abalorio Nido del ultimo dragon, ahora tiene un ICD (cd interno de uso) de 110 segundos y un 15% de prob de lanzarlo. mi punto es que estos abalorios caen en la misma raid alma y tienen efectos parecidos por ende su CI de 25 seg como esta actualmente esta mal y provoca un desbalance de clases por ejemplo magos y brujos con vortice transfigurador de almas entre otras clases se aprovechan de este bugg para hacer un dps elevado y constante en segundos en bgs o arenas, a mi parecer es de suma urgencia que se repare este bugg.

Saludos

**Comment by Jualk** [comment]
Leyendo foros sobre estos 2 abalorios y revisando el changelog del server, observo que hay un error en los Coldown internos (CI) de estos abalorios que según el changelog del server:
 
-INSIGNICA DE MENTE CORRUPTA(buscador, normal, heroico): tiene 25 segundos de cooldown interno y 15% de probabilidad de lanzarlo..
-VORTICE TRANSFIGURADOR DE ALMAS(buscador, normal, heroico): tiene 25 segundos de cooldown interno y 15% de probabilidad de lanzarlo.
-SELLO DE LOS SIETE SIMBOLOS (buscador, normal, heroico): tiene 25 segundos de cooldown interno y 15% de probabilidad de lanzarlo.

Basandome en lo leido en el foro:
http://es.wowhead.com/item=77991/insignia-de-mente-corrupta#english-comments http://es.wowhead.com/item=77990/vortice-transfigurador-de-almas#english-comments
http://es.wowhead.com/item=77969/sello-de-los-siete-simbolos#english-comments
Los CI Insignia de mente corrupta 115 seg. con 15% prob. lanzarlo, vortice transfigurador de alma 1min :45 seg con 15% de prob. lanzamiento y sello de los 7 simbolos de 2 minutos con 15% de prob. lanzamiento; son iguales o parecidos al arreglo del abalorio Nido del ultimo dragon, ahora tiene un ICD (cd interno de uso) de 110 segundos y un 15% de prob de lanzarlo. mi punto es que estos abalorios caen en la misma raid alma y tienen efectos parecidos por ende su CI de 25 seg como esta actualmente esta mal y provoca un desbalance de clases por ejemplo magos y brujos con vortice transfigurador de almas entre otras clases se aprovechan de este bugg para hacer un dps elevado y constante en segundos en bgs o arenas, a mi parecer es de suma urgencia que se repare este bugg.

Saludos

**Comment by rodrigoalv** [comment]
Se han efectuado los cambios

**Comment by Jualk** [comment]
Gracias :D
