### ISSUE TITLE
Bug (C.I.) Abalorios: Corazón de ira, Campana de resonancia enfurecedora, caída de mortalidad, Escencia de ciclón, Espejo de Theralion

### ISSUE THREAD

**Issue by Jualk** [steelwow/Bugtracker-434#156]
Buenas noches revisando foros y comprobado el uso de estos abalorios (ej. con mi maga equipada con el espejo de theralion y insignia de mente corrupta el primer abalorio me salta 3 hasta 4 veces en relación al segundo abalorio cosa que no deberia ser ya que tienen tiempos parecidos).

Adj. tiempo por cada abalorio.

-Corazón de ira (90 seg. y 10% de activación) http://es.wowhead.com/item=59224/corazon-de-ira#english-comments

-Campana de resonancia enfurecedora (90 seg. ) http://es.wowhead.com/item=59326/campana-de-resonancia-enfurecedora#english-comments

-Espejo de theralion (90 seg) http://es.wowhead.com/item=59519/espejo-de-theralion#english-comments

-Caida de Mortalidad (70 seg.) http://es.wowhead.com/item=65124/caida-de-mortalidad#english-comments

-Escencia de Ciclón (50 seg.) http://es.wowhead.com/item=65140/esencia-del-ciclon#english-comments

Bueno estos abalorios en especial campana de resonancia enfurecedora, corazón de ira y caída de mortalidad son bastante usados en arenas y bgs por el mismo bugg de tener un C.I. de 25 seg que presentaban los abalorios ya reparados de alma (Vórtice transfigurador de almas, sello de los 7 simbolos y Insignia de mente corrupta),lo que genera un aumento desproporcionado de poder con hechizos, poder de ataque, espiritu, etc si se activan el efecto de estos abalorios y  agregando la activacion de los distintivos de conquista, dominio o Victoria implacables o catas. Provocando un desbalance de clases en especial de las clases que se favorecen de dichos abalorios..

Saludos

**Comment by rodrigoalv** [comment]
Reparados.

Al reiniciar el server deberian estar correctos.
