### ISSUE TITLE
quest bug.... El desafio del valeroso (ventormenta)

### ISSUE THREAD

**Issue by fafaojeda** [steelwow/Bugtracker-434#157]
hice mis misiones diarias durante 5 dias para pasar la mision anterior y 3 dias mas para la anterior a esa!! q sucede la mision te pide q hables con "Escudero Danny" pero este no te permite seguir la mision!! 
![bug mision del valeroso](https://cloud.githubusercontent.com/assets/11387373/6552720/3f2ce83e-c61b-11e4-8065-c585768ff67d.png)

**Comment by GmTemis** [comment]
Solucionado
