### ISSUE TITLE
[Spell] Brujo

### ISSUE THREAD

**Issue by GmTemis** [steelwow/Bugtracker-434#171]
El hechizo Fuego de alma http://es.wowhead.com/spell=104027/fuego-de-alma

El hechizo Incinerar http://es.wowhead.com/spell=179095/incinerar

Se suben mucho debido a la maestría de demonologia http://es.wowhead.com/spell=77219/maestria-maestro-demonologo

Llegando apegar críticos de 64 a 98k Fuego de alma e incinerar críticos de 38k a 50k

**Comment by rodrigoalv** [comment]
Hola, se ha re-escripteado la maestria demonologia. Estara activa al reiniciar el servidor!
