### ISSUE TITLE
[Spell]Brujo

### ISSUE THREAD

**Issue by HermesGM** [steelwow/Bugtracker-434#173]
El hechizo Drenar alma http://es.wowhead.com/spell=103103/drenar-alma
Llena los tres cristales de alma del brujo sin haber muerto el objetivo, el hechizo especifica que esto ocurre solo si el objetivo que aporte experiencia u honor muere.

**Comment by rodrigoalv** [comment]
Hola, se ha reparado, cuando reinicie el server estara
