### ISSUE TITLE
[NPC] Npc's faltantes

### ISSUE THREAD

**Issue by HermesGM** [steelwow/Bugtracker-434#178]
Garyl <Vendedora de tabardos> http://es.wowhead.com/npc=5188/garyl
Maestro Pyreanor <Instructor de paladines> http://es.wowhead.com/npc=23128/maestro-pyreanor
Urtrun Aunaclanes <Maestro de hermandad> http://es.wowhead.com/npc=3370/urtrun-aunaclanes

**Comment by GmTemis** [comment]
Agregados
