### ISSUE TITLE
Spell: Palabra Sagrada Santuario (sacerdote sagrado)

### ISSUE THREAD

**Issue by Jualk** [steelwow/Bugtracker-434#179]
Esta sanación de areá esta over no sana según descripción 836p. por cada 2 segundos durante 18 seg. este hechizo esta curando 4k - 8k (aclaro mi sacer no esta full solo es impla-cat-soñoso, los full cataclismo curan mucho mas) adjunto imagen:

http://subefotos.com/ver/?edb29bd4a59bc748d6d6e62e956b10aco.jpg#codigos
- Changelog: Holy Word: Sanctuary 4.2.0 (Mon Jun 27 2011) Build 14107
  http://es.wowhead.com/spell=88686/palabra-sagrada-santuario#changelog

Saludos

**Comment by ghost** [comment]
Adjunto https://wow.freakz.ro/spells.php?spell=88685&name=holy-word-sanctuary

Blesses the ground with divine light, healing all within it for 327 (+4.2% SP) every 2 sec for 18 seconds. Only one Sanctuary can be active at a time. Healing effectiveness diminishes for each player beyond 6 within the area.

**Comment by rodrigoalv** [comment]
Se ha reaprado, cuando se reinicie el servidor estar opèrativo
