### ISSUE TITLE
Mazmorra boss bug

### ISSUE THREAD

**Issue by sabix** [steelwow/Bugtracker-434#182]
mazmorra
http://es.wowhead.com/zone=2367/antiguas-laderas-de-trabalomas

boss
http://es.wowhead.com/npc=18096/cazador-de-epoca

este boss no aparece ni en normal ni en heroico

**Comment by ghost** [comment]
Revisalo por que si aparece, solo hay que hacerlo bien

**Comment by GmTemis** [comment]
Investigue bien como se hace la mazmorra, esta totalmente funcional.

**Comment by sabix** [comment]
ps segun el mapa dice q esta en ese pueblo ... he ido  y no sale.... o no se si anda volando x ahi
