### ISSUE TITLE
Puntos conquista

### ISSUE THREAD

**Issue by biurnius** [steelwow/Bugtracker-434#184]
Hola hace tiempo los personajes de mi cuenta no reciben puntos de conquista por primera bg ganada en el dia y además no tengo índice de campo de batalla. por favor me gustaría que lo solucionarais.
mi cuenta es nachodela. gracias

**Comment by GmTemis** [comment]
No se solucionan problemas de cuentas específicos, estos temas al foro, cierro.

**Comment by ghost** [comment]
Es un problema que pasa a todos los pjs.
