### ISSUE TITLE
Misión Buegeada - Desafío valeroso

### ISSUE THREAD

**Issue by sharres** [steelwow/Bugtracker-434#186]
Esta misión la he corroborada con varios personajes de distinta razas y facciones.

esta misión situada en campo de torneo argenta en corona de hielo consta de derrotar a un cruzado argenta para ello primero hay que hablar con el escudero Danny, el problema es que este npc al momento de llegar a hablarle no da el paso seguir para proceder con la misión osea la batalla con el cruzado argenta.

**Comment by GmTemis** [comment]
Por favor proporcione algún link de la misión

**Comment by varelarg12** [comment]
http://es.wowhead.com/quest=13713/el-desafio-del-valeroso

**Comment by GmTemis** [comment]
Solucionado
