### ISSUE TITLE
[Instance/Logro] Uldaman

### ISSUE THREAD

**Issue by ghost** [steelwow/Bugtracker-434#19]
http://es.wowhead.com/zone=1337

Vigilante de piedra http://es.wowhead.com/npc=4857 no sale, accionando la piedra del centro deberia de salir y al matarlo abrir la puerta siguiente para matar a Archaedas, el boss final y que da logro de mazz.

**Comment by smiedth** [comment]
Deberían dejar la puerta abierta para llegar a  Archaedas sin problemas

**Comment by GmTemis** [comment]
Reparado
