### ISSUE TITLE
Presura Mental Chaman Mejora

### ISSUE THREAD

**Issue by elsharky** [steelwow/Bugtracker-434#195]
PResura Mental: ahora tu poder con hechizos es igual a un 55% de tu poder de ataque y ya no te beneficias de otras fuentes de poder con hechizos. Tambien reduce un 75% el coste de mana de tus hechizos instanteneos beneficios, dañinos o de totem.

Bien... hace unos meses que el chaman mejora vuelve a estar sin ese poder y con el bajo daño y curacion que ahora tiene (siendo una clase melee y estar al centro de la pelea) pierde mucha supervivencia con ello y quisiera que por favor lo vean

Hace mas o menos un mes se arreglo 2 poderes de la clase chaman que estaban overbug
Cadena y descarga de relampagos de la rama elemental y Curaciones de la rama Restauracion: creo que solo bajaron los numeros ya que ahora va bien en sus respectivas ramas pero en Mejora se nerfeo completamente!

Siendo una habilidad principal ya que el chaman mejora se caracteriza por ser un melee que puede atacar a distancia y curarse pero anda recontra nerf ni para cosquillas xD

descarga y cadena de relampagos:
Hace un promedio de 800 a 1000 de daño

curaciones:
Ola de SAnacion superior (la mas fuerte) de 11mil con 3 segundos de casteo (7.5mil coste de mana)
ola de sanacion (la mediana) 6mil de curacion (pide poco 2mil de mana)
Ola de sanacion inferior (la menor) 8mil de curacion (pide 5mil de mana)
no vale la pena ni siquiera castearlo...

**Comment by elsharky** [comment]
Esto ya se posteo desde Dream y a la fecha nada... Es de vital importancia este poder para un chaman mejora puesto que sin ello le quitan bastante supervivencia!!! curas de 11mil con Ola de sanacion superior que tiene tiempo de casteo de casi 3 segundos!!?? porfavor el staff ponerse serios con estas cosas que dejan muy de lado habiendose posteado desde hace mucho

**Comment by elsharky** [comment]
https://github.com/steelwow/Bugtracker-434/issues/177

**Comment by rodrigoalv** [comment]
Hola, presura mental se ha reparado ahora toma correctamente el 55% de poder con hechizos de poder de ataque.
