### ISSUE TITLE
[Spell/Talento]Paladin

### ISSUE THREAD

**Issue by HermesGM** [steelwow/Bugtracker-434#204]
El hechizo Choque sagrado (http://es.wowhead.com/spell=20473/choque-sagrado)deberia dar una carga de poder sagrad ocada que se utiliza, actualmente aveces no la da, y otra veces la da, pero se va inmediatamente la carga cosa que no deberia pasar.
El talento Torre de Radiancia, con sus 3 puntos, deberia tener un 100% de posibilidades de otorgar una carga de poder sagrado cada vez  que usa destello de luz o luz divina, de momento no da dicha carga con ninguno de los dos hechizos

**Comment by rodrigoalv** [comment]
se ha reparado
