### ISSUE TITLE
Cadena de misiones de Karazhan

### ISSUE THREAD

**Issue by Wengael** [steelwow/Bugtracker-434#205]
Resucitar el pasado, la misión anterior del diario de Medivh esta super bien se ve la pelea de el con el Dragón y como le expulsa, pero luego la que hay que buscar el trozo de hueso carbonizado en el sitio, 45- 78,8 no está y no se puede continuar
![wowscrnshot_040815_215839](https://cloud.githubusercontent.com/assets/7965365/7059679/79cf314a-de3a-11e4-9a4e-065d67e271e9.jpg)
![wowscrnshot_040815_215830](https://cloud.githubusercontent.com/assets/7965365/7059680/79d04472-de3a-11e4-89f4-32455c50f836.jpg)

**Comment by GmTemis** [comment]
Solucionado
