### ISSUE TITLE
BUG en estadistica todas las clases

### ISSUE THREAD

**Issue by sabix** [steelwow/Bugtracker-434#207]
Penetración de hechizo
no sube... arreglen eso...

todos mis pjts tienen 0 en penetracion de hechizo apezar de tener gemas o items para subir la estadistica....

**Comment by llSeanll** [comment]
Creo que es visual, porque tanto cazadores como caster tienen un daño "elevado" a pesar de la cantidad de Temple/Armadura/Aguante que tenga el objetivo.

**Comment by GmTemis** [comment]
Sin fotos o soporte no hay reporte,
