### ISSUE TITLE
Campo de batalla: La batalla por gilneas

### ISSUE THREAD

**Issue by aratroc** [steelwow/Bugtracker-434#214]
como sabemos hace poco se ha implementado este campo de batalla pero hay un bug muy serio que a toda la comunidad le ha traido problemas, y es que luego de que una faccion toma una base se hace imposible poder "robarla"
y practicamente ademas de ser una perdida de tiempo en el caso de que la faccion a la que uno pertenesca no pueda tomar 2 bases

**Comment by rodrigoalv** [comment]
Se han reparado cementerios y este problema
