### ISSUE TITLE
Problema con Hermandad

### ISSUE THREAD

**Issue by llSeanll** [steelwow/Bugtracker-434#215]
Las Hermandades son una herramienta importante en el servidor para la interacción entre usuarios, además, favorece a la comunidad al ser el alojamiento de usuarios que migran a esta. Por tanto, la funcionalidad de esta debería ser de gran prioridad para quienes reparan el servidor.

Los siguientes son problemas generales de las hermandades:
- La reputación con hermandad sólo se puede obtener mediante misiones diarias en Tol'Barad.
- Sólo hay una cantidad limitada (5-10 logros) de logros para obtener como hermandad.
- La posibilidad de reparar equipamiento utilizando el dinero de la Hermandad no funciona.
# 

![wowscrnshot_042215_215348](https://cloud.githubusercontent.com/assets/1500817/7288645/fd5ec522-e932-11e4-85e0-78a21004be69.jpg)
![wowscrnshot_042215_215335](https://cloud.githubusercontent.com/assets/1500817/7288644/fd5ee1ba-e932-11e4-8079-386a95cf270a.jpg)
# 

Personalmente, me favorece la posibilidad de obtener logros como Hermandad, ya que, permitiría la posibilidad de crear eventos, premiar y felicitar a miembros de esta por su trabajo. Obtener reputación con la Hermandad da una posibilidad de obtener jerarquía dentro de una Hermandad.

**Comment by rodrigoalv** [comment]
-> lo de reputacion con hermandades esta reparado, se podra obtener atraves de misiones comunes y corrientes
