### ISSUE TITLE
Astucia del Cruel (abalorio)

### ISSUE THREAD

**Issue by Melenaris** [steelwow/Bugtracker-434#220]
Descripcion:  Tus hechizos dañinos tienen una probabilidad de activar una Salva de Descarga de las Sombras que inflige xxxx p. de daño a todos los enemigos en un radio de 10 m de tu objetivo actual.

Problema. El abalorio en si se activa correctamente y el daño es correcto, el problema q tiene es que su CD interno no es correspondiente a la version de juego que el server esta utilizando. Este abalorio apartir del la version 4.3.2 paso a tener un ICD de 9 segundos y aqui sigue poseyendo un ICD de 25 segundos como en las versiones previas a la ya mensionada.

PD: En la descripcion del daño puse XXXX porque su daño aumenta o diminuye en funcion al equipo.

Link de wowhead: http://www.wowhead.com/item=77208/cunning-of-the-cruel

**Comment by timh52280** [comment]
Si tienes razon el ICD en esta versión es de 9 segundos ya se ha hecho la reparación, en el próximo reinicio del servidor ya se aplicará el nuevo ICD saludos.

**Comment by Melenaris** [comment]
Muchas gracias por su atencion.
