### ISSUE TITLE
NPC's faltantes en Orgrimmar

### ISSUE THREAD

**Issue by Drewdai** [steelwow/Bugtracker-434#221]
Hola, de nuevo han desaparecido los siguientes 3 PNJ's en Orgrimmar, dejo el link y la imagen como prueba de que no están.
1. Urtrun Aunaclanes (Maestro de hermandad)
   -> http://es.wowhead.com/npc=3370/urtrun-aunaclanes
   -> http://goo.gl/lqcD3B
2. Garyl (Vendedora de tabardos)
   -> http://es.wowhead.com/npc=5188/garyl
   -> http://goo.gl/QHRu7b
3. Maestro Pyreanor (Instructor de paladines)
   -> http://es.wowhead.com/npc=23128/maestro-pyreanor
   -> http://goo.gl/IqM8ST

Espero puedan ponerlos pronto, saludos

**Comment by GmTemis** [comment]
Solucionado
