### ISSUE TITLE
Cadena de Quest Karazhan

### ISSUE THREAD

**Issue by Miguelscott** [steelwow/Bugtracker-434#222]
Hola equipo de Steelwow; me gustaría agradecerles por reparar la cadena de quest de Karazhan, solo que la última quest [Nightbane] ó [Nocturno] no anda; la quest la da una NPC llamada Kalynna y se encuentra en Area 52; se debe de utilizar urna ennegrecida que se encuentra en el bancal del maestro en Karazhan y la urna no da la opción de usarla para invocar al dragón. Muchas gracias por su atención.

Att: Sylviana

**Comment by GmTemis** [comment]
Tema repetido
