### ISSUE TITLE
Bug T.N.T. (talento caza survival)

### ISSUE THREAD

**Issue by Epicscorp** [steelwow/Bugtracker-434#224]
Descripción: Cuando inflinges daño periódico con Trampa de inmolación, Trampa explosiva o Flecha negra tienes un 20% de activar Bloquear y cargar.
Los ultimos 2 dias he estado jugando en la rama supervivencia del cazador y me he dado cuenta que el  talento T.N.T. no funciona, ha estado el dot de flecha negra siempre pero nunca se activa, asi que probe en los muñecos de orgrimmar con la trampa explosiva y aun pegandole a los 3 muñecos se agotaba la trampa pero no saltaba el talento.
Sugiero que se arregle debido a que es una skill que se usa bastante en la rama survival.

**Comment by timh52280** [comment]
Se ha reparado el talento, revisar su funcionamiento cuando aparezca en el changelog.
