### ISSUE TITLE
Formula temple

### ISSUE THREAD

**Issue by Jualk** [steelwow/Bugtracker-434#225]
Buenas googleando encontre formula de temple a ver si son de ayuda:

y = 1 - 0.99 ^ ( x / 79.12785 )

Fuente: http://www.wowwiki.com/Resilience

La siguiente basada en un apartado de un jugador en foro del oficial:

% = 100 a 100 \* 0.99 ^ (índice de temple / 79.12785)

porcentajes de salud eficaces utilizando esta fórmula:
100 / (1- [reduc dmg% / 100])

Fuente: http://us.battle.net/wow/en/forum/topic/3229086381

Saludos

**Comment by timh52280** [comment]
Eso es solo para que te de el porcentaje de mitigamiento es decir el % que te aparece en el tooltip,

**Comment by rodrigoalv** [comment]
cierro ya que no es la formula
