### ISSUE TITLE
[Misión] "La carga del Valeroso" en Torneo Argenta

### ISSUE THREAD

**Issue by ghost** [steelwow/Bugtracker-434#23]
Esto es un error en 5 NPCS que no dan misiones y no dejan hacer otras 5 misiones, un total de 10 afectadas. Concretamente faltan todas las misiones que deberian dar sellos valerosos, pero reporte por reporte (http://es.wowhead.com/item=44987/sello-de-valeroso).

En el caso de Lugargenta: Kethiel Lanzasol (http://es.wowhead.com/npc=33538/kethiel-lanzasol#starts) deberia dar una misión diaria (http://es.wowhead.com/quest=13786) para conseguir los Sellos de Valeroso para completar la mision de Carga del Valeroso que se puede cojer (http://es.wowhead.com/quest=13722) y da Eressea Cantoalba (http://es.wowhead.com/npc=33379).

En el caso de Entrañas: Sarah Chalke (http://es.wowhead.com/npc=33541/sarah-chalke) deberia dar http://es.wowhead.com/quest=13781 para http://es.wowhead.com/quest=13721 de Mortacechador Visceri.

En el caso de Orgrimmar: Akinos (http://es.wowhead.com/npc=33405/akinos) deberia dar http://es.wowhead.com/quest=13765 para http://es.wowhead.com/quest=13697 de Mokra el Trituracráneos.

En el caso de Cima del trueno: Dern Tótem de Ira (http://es.wowhead.com/npc=33539/dern-totem-de-ira) deberia dar http://es.wowhead.com/quest=13776 para http://es.wowhead.com/quest=13720 de Runok Ferocrín.

En el caso de Sen´jin: Cazador de las Sombras Mezil-kree (http://es.wowhead.com/npc=33540/cazador-de-las-sombras-mezil-kree) deberia dar http://es.wowhead.com/quest=13771 para http://es.wowhead.com/quest=13719 de Zul'tore.

Se arreglaron las de Alianza pero no Horda.

**Comment by GmTemis** [comment]
Reparado

**Comment by ghost** [comment]
Sigue igual.
