### ISSUE TITLE
Ropa nivel 70 para pj lvl 1

### ISSUE THREAD

**Issue by resarce** [steelwow/Bugtracker-434#232]
Les reporto lo siguiente, Ya que se acerca el evento twink lvl 19 en el servidor para que no  se les pase esto  en la zona de los dk hay un npc que vende armadura de placas anillos capas abalorios y armas lvl 55 a lvl 70  y no tienen nivel requido lo cual  es posible usar dichos itens a si sea lvl 1 el pj  por lo tanto mas de uno querra pasarse de listo y llevar dichos objetos asi que atentos.
les dejo foto de el npc y algunos obejtos.

http://es.tinypic.com/r/hug5rq/8
http://es.tinypic.com/r/flkrbn/8

**Comment by GmTemis** [comment]
Se ha eliminado el npc mientras el evento, se revisara el equipo antes de comenzar el evento para evitar fraudes.
