### ISSUE TITLE
Ataque de la victoria

### ISSUE THREAD

**Issue by aratroc** [steelwow/Bugtracker-434#236]
esta skill sana al guerrero un cierto %
pero actualmente esta sanando mucho, he llegado a ver casos en los cuales un war se helea sobre 180k
tanto en arenas como en bgs
en resumen sanacion over

**Comment by rodrigoalv** [comment]
Hola:

Necesitamos para esto ver una imagen o video, ya que segun formula se debe sanar el 20% de la vida del guerrero, en formula deberia estar bien
