### ISSUE TITLE
Murallas del Fuego Infernal -boss bug 

### ISSUE THREAD

**Issue by xllhassamllx** [steelwow/Bugtracker-434#237]
Una mazmorra llamada Murallas del Fuego Infernal  tiene un boss llamado Vazruden el Heraldo , matando a este boss y a su dragon nos deberia sacar un cofre para ver que a caido del boss y asi obtener un arma de asta llamado Saqueadora infernal  que muchos cazadores que conosco la quisieron pero , el boss esta bug porque no saca el cofre para lotear ,  hay amigos antiguos del servidor que si tienen esta arma de asta porque antes no andaba bug , quisiera que lo arreglen porfavor , gracias

**Comment by GmTemis** [comment]
Hola te agradecemos, que pongas alguna foto o video
