### ISSUE TITLE
Propulsiones de nitro - Ingenieria 

### ISSUE THREAD

**Issue by xllhassamllx** [steelwow/Bugtracker-434#238]
este es un poder especial de ingenieria que lo compones a  tu cinturon  , te hace veloz durante 5 sg pero lamentablemente se encuentra bug porque a todos que conosco con este cinturon de Propulsiones de nitro - Ingenieria   aveces en vez de correr rapido nos eleva al cielo , muy alto que si no tienen paracaidas se mueren , eso pasa aveces , aveces esta bien , aveces te eleva al cielo , porfavor arreglen este bug porque es fastidioso que en duelo o en una bg te pase eso.

**Comment by Drewdai** [comment]
Hola, es natural que falle y no solo aquí pasa, tengo 3 ingenieros y con todos uso propulsores, de 10 veces que lo uso 2 veces me falla. No creo que sea un bug porque de hecho el item te advierte que puede variar e incluso fallar, pero en fin, espero si está mal lo analicen. Saludos! :)

**Comment by rodrigoalv** [comment]
Hola:

El spell funciona correctamente, y efectivamente en algunos casos te tira hacia arriba.
