### ISSUE TITLE
bug en la mazmorra murallas de fuego infernal

### ISSUE THREAD

**Issue by hyno1999** [steelwow/Bugtracker-434#239]
bueno este es mi posteo  en la mazmorra murallas de fuego infernal en el bos vazruden el herlado  no se puede abrir el cofre  voy dias intentando y no se puede abrir el cofre x favor reparenlo q yo  y mis amigos andamos aciendo  mazmorras para  sacar ropa de transfiguracion  y esto nos dificulta   quiero ser feliz gracias !!

**Comment by xllhassamllx** [comment]
Tambien reporte esto y aunque es facil de entenderlo dijeron qur ponga una foto del boss bug y cerraron el reporte uu . Hynox :3 soy has

**Comment by hyno30000** [comment]
mmm
espero q lo resulvan este problea x fa!!!

**Comment by GmTemis** [comment]
Por favor agradecemos fotos o algo que documente el daño les recordamos las reglas de posteo aquí.

https://github.com/steelwow/Bugtracker-434
