### ISSUE TITLE
bug  en la banda de ulduar 10n

### ISSUE THREAD

**Issue by hyno30000** [steelwow/Bugtracker-434#240]
mi posteo es de   ulduar  en modo 10n q comandante de expedicion no se activa para el bos  voy intentando dias aver si se activa y nada x favor solucionen ese problema gracias........si no me equivoco es el 3er bos en ulduar y gracias x solucionar ese bug

**Comment by Drewdai** [comment]
Toda la raid está bug.

**Comment by GmTemis** [comment]
Por favor agradecemos fotos o algo que documente el daño les recordamos las reglas de posteo aquí.

https://github.com/steelwow/Bugtracker-434
