### ISSUE TITLE
 [Disipar magia]

### ISSUE THREAD

**Issue by makavelo00** [steelwow/Bugtracker-434#257]
gm  el poder  [Disipar magia] no sirve i cuando metes el glifo  [Glifo de Disipar magia] tendria que curarte el 3% de de tu salud maxima http://es.wowhead.com/item=42415/glifo-de-disipar-magia   areglalo gm no se deja usar ese poder grax :)

**Comment by makavelo00** [comment]
el poder nose deja usar cuando estas en sombra

**Comment by rodrigoalv** [comment]
se ha reparado
