### ISSUE TITLE
Cazador Punteria

### ISSUE THREAD

**Issue by razielassamita** [steelwow/Bugtracker-434#262]
No sé exactamente por qué, pero de nuevo hay enfoque infinito, al lanzar disparo de punteria, se gasta el enfoque (50) pero inmediatamente se recupera, es decir, se puede spammear Disparo de Punteria sin ningún problema... algo anda mal... lo pongo de una vez antes de q empiecen a entrar solo cazas al server por este bug.

Muchas gracias

**Comment by Xioremi** [comment]
eso ya feu reparado
