### ISSUE TITLE
Mision bug 

### ISSUE THREAD

**Issue by amortis010** [steelwow/Bugtracker-434#267]
![jeje](https://cloud.githubusercontent.com/assets/12701422/7920040/f3331776-0861-11e5-8f9a-c9deaabf3754.jpg)
![lol](https://cloud.githubusercontent.com/assets/12701422/7920042/f339e060-0861-11e5-93d7-9f0843b45c2e.jpg)
![xd](https://cloud.githubusercontent.com/assets/12701422/7920041/f339e196-0861-11e5-86ca-9469605c4853.jpg)

**Comment by GmTemis** [comment]
Ya esta reportado en el bugtracker, a la espera de reparacion
