### ISSUE TITLE
Wowerror en en banco

### ISSUE THREAD

**Issue by razielassamita** [steelwow/Bugtracker-434#273]
Bueno, esto es conocido desde hace mucho, la cosa es q quiero colaborar con mi hermandad, pero es bastante molesto q el 80% de las veces q hago algo en el banco de hermandad me bota del server, es sobretodo molesto cuando haces cola de bg o algo asi... 

Seria bueno q intentaran reparar este detalle...

Muchas gracias

**Comment by GmTemis** [comment]
Esto se debe al cliente de juego.
