### ISSUE TITLE
[Instance/Logro] Stratholme

### ISSUE THREAD

**Issue by ghost** [steelwow/Bugtracker-434#32]
http://es.wowhead.com/zone=2017

Lord Aurius Osahendidohttp://es.wowhead.com/npc=45412 no cuenta para el logro de la mazz aunque lo mates. http://es.wowhead.com/achievement=646

**Comment by Ylonen** [comment]
No cuenta porque no es el npc que deberíamos tener. En el server tenemos al Baron Osahendido http://es.wowhead.com/npc=30549 (igual no es este npc, solo que el que tenemos ya no existe en wowhead) que es el que estaba en la WOTLK pero fue reemplazado por Lord Aurius Osahendido http://es.wowhead.com/npc=45412 en CATACLYSM :3

**Comment by rodrigoalv** [comment]
Se ha reparado, probarlo cuando este en el changelog.

**Comment by ghost** [comment]
Se han realizado otros cambios, pero este sigue sin ir.

**Comment by rodrigoalv** [comment]
gynevra cuando este en el changelog :D 
lo que pasa que no hemos subido cambios al servidor, por lo mismo no se a puesto esto, esperamos esta semana subir todos los que tenemos en cola :)

saludos

**Comment by ghost** [comment]
Oookey, como antes no poniais todo en detalle en el changelog... todo correcto
