### ISSUE TITLE
[Misión] Quest dagas legendarias

### ISSUE THREAD

**Issue by ghost** [steelwow/Bugtracker-434#34]
1 Mision http://es.wowhead.com/quest=29801 La primera quest se coge al hablar con Lord Afrasastrasz justo en la entrada de la nueva banda “Alma de dragón”. La quest es bastante fácil y lo único que hay que hacer es robar a Hagara (cuarto boss). Obtendremos un anillo que deberemos entregar a Lord Afrasastrasz.
Una vez entreguemos el anillo nos darán la segunda quest donde deberemos cargar el anillo. FUNCIONA

2 Mision http://es.wowhead.com/quest=29802 Debes llevar el anillo al tumaturgo de tu capital para recargarlo,en mi caso es el tumaturgo Altha,soy horda.Al hablar con el npc no sucede nada. NO FUNCIONA

Demuestra lo que vales [Funciona]
Un mensaje escondido[No Funciona]
A Ravenholdt [No Testeado]
Cazar al ladrón [No Testeado]
Nuestro hombre en Gilneas [No Testeado]
Asesinar a Creed [No Testeado]
Ya está hecho, recompensa - Miedo y Venganza [No Testeado]
Por un puñado de gemas [No Testeado]
Nuestro hombre en Karazhan [No Testeado]
La sangre de la traidora [No Testeado]
Victoria en las profundidades, recompensa - La Durmiente y La Soñadora [No Testeado]
Afílate los colmillos [No Testeado]
Parricidio, recompensa - Golad, Crepúsculo de los Aspectos, Tiriosh, Pesadilla de los Tiempos [No Testeado]

Ahora mismo, se podria hacer hasta la misión victoria en las profundidades, ya que para las dos últimas dagas hacen falta el colmillo de alamuerte.

He tenido la oportunidad de probar las ultimas dagas en el beta, y funcionaban correctamente.

Serie genial una implantación progresiva para las dagas en lugar de ponerlas de golpe, es decir, primero las 7 primeras misiones para conseguir las primeras, mas adelante las otras 4, y en una fase final las 2 ultimas.

**Comment by steelwow** [comment]
exacto, creemos que sera como dices, durante esta semana dejaremos las primeras misiones funcionales :D

**Comment by ghost** [comment]
Como parece que ya funciona la cadena, asique...
