### ISSUE TITLE
[Hechizo] Desenredo || Druida

### ISSUE THREAD

**Issue by llSeanll** [steelwow/Bugtracker-434#39]
Descripción:
 Es una habilidad pasiva específica de la especialización Restauración.

 Al cambiar de forma -el Druida Restauración- elimina todos los efectos de frenado y relentización.
# 

Problemas:
- Las especialización de Balance y Feral se benefician de esta habilidad pasiva. 
# 

![wowscrnshot_010515_175133](https://cloud.githubusercontent.com/assets/1500817/5619733/88cfe908-9503-11e4-97e6-06cb87230e8d.jpg)

En esta imagen podemos ver la habilidad exclusiva de la especialización de Restauración.

**Comment by GmTemis** [comment]
Saludos, Te agradecemos por favor que uses un soporte visual (Video, Imagenes), para completar tu reporte.

**Comment by llSeanll** [comment]
Enviada la imagen. Si se necesita más información de este problema, favor de contactar conmigo vía RaidCall, Horda(Buaf), Alianza(Sean). Así podremos testear In-Game el problema.
