### ISSUE TITLE
[Talento] Presteza feral || Druida

### ISSUE THREAD

**Issue by llSeanll** [steelwow/Bugtracker-434#40]
Descripción:
  Talento perteneciente a la especialización Feral.

  Permite eliminar efecto de relentización y frenado al utilizar Carrerilla, además, si se utiliza Rugido de estampida los aliados cercanos también eliminan relentización y frenado.
# 

Problemas:
- Los Druidas que no tengan este talento activado igual pueden tener beneficio de su acción.
# 

![wowscrnshot_010515_175328](https://cloud.githubusercontent.com/assets/1500817/5619769/cb4cda2a-9503-11e4-8ea3-9b8afa685bba.jpg)

Aquí podemos ver el Talento perteneciente a la Rama Feral.

**Comment by GmTemis** [comment]
Saludos, Te agradecemos por favor que uses un soporte visual (Video, Imagenes), para completar tu reporte.

**Comment by llSeanll** [comment]
Enviada la imagen. Si se necesita más información de este problema, favor de contactar conmigo vía RaidCall, Horda(Buaf), Alianza(Sean). Así podremos testear In-Game el problema.

**Comment by rodrigoalv** [comment]
se ha reparado
