### ISSUE TITLE
[Talento] Toque potenciado || Druida Restauración

### ISSUE THREAD

**Issue by llSeanll** [steelwow/Bugtracker-434#41]
Descripción:
  Aumenta la sanación directa de los hechizos Toque de sanación, Recrecimiento y Nutrir, además, otorga a estos hechizos la posibilidad de reiniciar la duración de Flor de Vida sobre los objetivos.

  Al tener 1 punto de Talentos, la sanación aumenta un 5% y la probabilidad es de 50%. Mientras que al tener 2 puntos de Talentos, la sanación aumenta un 10% y la probabilidad es de 100%.
# 

Problemas:
- No hay efecto de aumento de sanación directa del 10%.
- No reinicia el efecto de Flor de Vida sobre los objetivos, teniendo 2Pts de Talentos.
# 

![wowscrnshot_010515_175516](https://cloud.githubusercontent.com/assets/1500817/5619801/18c86cec-9504-11e4-8e54-c66d35f864b4.jpg)

Acá vemos la descripción del Talento en cuestión.

**Comment by GmTemis** [comment]
Saludos, Te agradecemos por favor que uses un soporte visual (Video, Imagenes), para completar tu reporte.

**Comment by llSeanll** [comment]
Enviada la imagen. Si se necesita más información de este problema, favor de contactar conmigo vía RaidCall, Horda(Buaf), Alianza(Sean). Así podremos testear In-Game el problema.

**Comment by rodrigoalv** [comment]
@llSeanll  testarlo bien y reportarlo

yo lo he testeado hoy, y esta correcto.
