### ISSUE TITLE
[Item] Nido del ultimo dragon.

### ISSUE THREAD

**Issue by Melenaris** [steelwow/Bugtracker-434#44]
![wowscrnshot_010515_181018](https://cloud.githubusercontent.com/assets/9995913/5620002/27d576c4-9506-11e4-9996-1bdf7b0e1d5e.jpg)
![wow 2](https://cloud.githubusercontent.com/assets/9995913/5620158/d80ba4c2-9507-11e4-8726-8c771990fde5.jpg)
![wow 3](https://cloud.githubusercontent.com/assets/9995913/5620162/eab467da-9507-11e4-892a-0cf2c7fc3947.jpg)
![wow 4](https://cloud.githubusercontent.com/assets/9995913/5620168/fbb1ed78-9507-11e4-9003-1bc6d5a810b4.jpg)
![wow 5](https://cloud.githubusercontent.com/assets/9995913/5620178/1362408a-9508-11e4-8ce1-0f0040948bcd.jpg)

Descripcion:  Cuando infliges daño tienes una probabilidad de obtener 2904 p. de golpe crítico durante 20 s.

Problema: El respectivo abalorio carece de Cooldown/CD (Enfriamiento) interno, Es decir se activa practicamente en todo momento(Foto 2 y Foto 3).
 Ademas que no solo se activa cuando el usuario del abalorio inflige daño sino que tambien cuando le infligen daño al jugador( Foto 4 y Foto 5).Esto no solo sucede con este abalorio sino tambien con todos los abalorios de Alma de Dragon, los cuales sus efectos se basan en probabilidades como medio de activacion.

Aqui dejo el link de wowhead: http://es.wowhead.com/item=77972

**Comment by Melenaris** [comment]
Aver cuando arreglan este puto abalorio de 1 ves por todas. Ya lleva mas de 1 mes el reporte de esta mierda que desbalancea todo. Tanto el pvp como el pve.

**Comment by GmTemis** [comment]
Reparado No hay necesidad de usar groserías.
