### ISSUE TITLE
[Habilidad] Redirigir (Pícaro)

### ISSUE THREAD

**Issue by sergioadivina** [steelwow/Bugtracker-434#45]
Esta habilidad al usar sobre un objetivo que ya tiene puntos de combo los duplica y no debería hacer nada sobre alguien que ya tiene puntos de combo.

**Comment by GmTemis** [comment]
Por favor ponga algún elemento visual que sustente el error

**Comment by rodrigoalv** [comment]
Se ha reparado. cuando este en el changelog estara disponible
