### ISSUE TITLE
[Habilidad] Emboscada (Pícaro)

### ISSUE THREAD

**Issue by sergioadivina** [steelwow/Bugtracker-434#46]
Pega mucho menos de lo que debería. Aquí os dejo el enlace de la formula en el changelog de wow head para que veáis la formula http://es.wowhead.com/spell=8676#changelog y si me poneis en un comentario como va os hago el calculo que no la entiendo xD.

**Comment by GmTemis** [comment]
Por favor ponga algún elemento visual que sustente el error

**Comment by Enigma77** [comment]
![asd](https://cloud.githubusercontent.com/assets/7662334/5630316/67f2a64c-959b-11e4-8d57-667c5028ec87.png)

**Comment by rodrigoalv** [comment]
@Enigma77  tu formula esta incorrecta.

el daño es asi
1.- Si no hay daga equipada = (190% \* dañodearma) + 367 puntos

2.- Si hay daga equipada = ((190%*daño de arma) +367) \* 1.147

 que seria lo mismo a
(190 \* 1.147)% \* daño arma + (367 \* 1.147) que quedaria

(217.93% \* daño arma) + (420, 949)

en ningun momento el daño de arma es 367% este valor es un plus al daño, un valor base en la formula

verificar, puesto que lo que yo creo, es que al tener dagas equipadas no aumenta el daño que deberia 

espero confirmacion @sergioadivina @enigma77

**Comment by sergioadivina** [comment]
![wowscrnshot_012215_123438](https://cloud.githubusercontent.com/assets/7648398/5854961/5faa1ab6-a233-11e4-98a5-f36e5be0dfad.jpg)

Esta es la formula ingame y creo como dice enigma que al usar dagas se le da un % mayor al daño con emboscada igual que pasa con hemorragia para que los daños no quedaran muy por debajo del daño que haces cuando usas espada pero yo recuerdo en el ofi meter mas de emboscada con una espada que con una daga.
Mis stats:
Daño de arma con espada: 4900 aproximadamente
Daño al muñeco de entrenamiento con espada: 28963 (critico)
Daño de arma con daga: 3300 aproximadamente
Daño al muñeco de entrenamiento con daga: 20857 (critico)
Cálculos según formula ingame:
-Con espada:
(276% del daño de arma) + 1115 = 13524 + 1115 = 14639 y un 45% mas por talentos = 21226,55(no critico) - 42453,10 (critico aproximado)
-Con daga:
(399% del daño de arma) + 1613 = 13167 + 1613 = 14780 y el 45% = 21431 (no critico) - 42862 (critico aproximado)
Cálculos según formula de troxx (Que tiene bastante sentido xD):
-Con espada:
(190% del daño de arma) + 367 = 9310 + 367 = 9677 + 45% = 14031,65 (no critico) - 28063,30 (critico aproximado)
-Con daga:
(217.93% del daño de arma) + 420, 949 = 7612,64 + 45% = 11038,32 (no critico) - 22076,64 (critico aproximado)

**Comment by rodrigoalv** [comment]
hola:

la formula que coloque yo es la que tenemos como base:

sin daga: (190% \* daño arma) + 367
con daga: ((190% \* daño arma) + 367)\* 1.447 **\* el valor 1.147 era en realidad 1.447 error de tipeo

Esta formula es la base de emboscada. (si eliminais todos los talentos vereis esta formula exceptuando que cambia el valor de normalizacion de daño de arma (367 por 699 en el caso sin daga y 1011 en caso de con daga)

debeia ser la formula asi:

sin daga: (190% \* daño arma )+699
con daga : (190%_daño arma \* 1.447) + 699 \* 1.447
            (275%_daño arma) + 1011

Esta formula es la formula base de emboscada

Segun lo investigado, en la formula que me pone @sergioadivina
implica la suma de los beneficios como emboscada mejorada (%)
por lo cual hay que entrar a establecer cuales son los talentos que mejoran el daño de emboscada
para scriptearlos, ya que por lo que noto, el daño es el basico y no aumenta con los talentos.

Saludos
Troxx.

**Comment by sergioadivina** [comment]
Los talentos son "Emboscada mejorada" y "oportunidad" que están en la rama sutileza al principio.

**Comment by rodrigoalv** [comment]
@sergioadivina he echo un script de prueba, avisa por ticket cuando estes online y hablamos para probarlo en el reino test.

**Comment by rodrigoalv** [comment]
Se ha reparado. cuando este en el changelog estara disponible
