### ISSUE TITLE
[Talento] Impacto (Mago/fuego)

### ISSUE THREAD

**Issue by sergioadivina** [steelwow/Bugtracker-434#49]
Cuando se activa no reinicia la duración de explosión de fuego y ademas no propaga los efectos de daño en el tiempo a los objetivos cercanos.

**Comment by GmTemis** [comment]
Por favor ponga algún elemento visual que sustente el error

**Comment by rodrigoalv** [comment]
se ha reparado cuando este en el changelog estara disponible
