### ISSUE TITLE
[Habilidad] Cambio de forma (Druida/feral)

### ISSUE THREAD

**Issue by sergioadivina** [steelwow/Bugtracker-434#55]
El druida feral actualmente cuando cambia de forma se esta quitando los efectos inmovilizadores y no debería, solo debe quitarte los que te ralentizan. Los inmovilizadores solo se pueden quitar si estas en la rama restauración.

**Comment by llSeanll** [comment]
Hola, tanto el Druida Balance como el Druida Feral pueden quitarse efectos de relentización e inmovilización (Entiéndase como aquello que no silencia pero detiene) al tener activo el Talento "Presteza feral".

La acción que permite quitarse estos efectos al cambio de forma pertenece sólo a la habilidad pasiva "Desenredo" (que es lo que falla), la cual es exclusiva de la rama Restauración.

**Comment by GmTemis** [comment]
Por favor ponga algún elemento visual que sustente el error

**Comment by rodrigoalv** [comment]
se ha reparado cuando reinicie el servidor estara disponible
