### ISSUE TITLE
[Talento] Avance de la muerte (Dk/Profano)

### ISSUE THREAD

**Issue by sergioadivina** [steelwow/Bugtracker-434#56]
Esta habilidad solo debería activarse cuando te quedas sin ninguna runa profana y se activa cuando te falta cualquiera de las runas aunque solo sea 1 de otro tipo lo que imposibilita pillar a un dk profano.

**Comment by GmTemis** [comment]
Por favor ponga algún elemento visual que sustente el error

**Comment by rodrigoalv** [comment]
se ha reparado estara disponible cuando este en el changelog
