### ISSUE TITLE
Bug Presura Mental Chaman Mejora

### ISSUE THREAD

**Issue by elsharky** [steelwow/Bugtracker-434#61]
Anteriormente estaba bug "PRESURA MENTAL" en el chaman mejora ya que los daños y curaciones eran muy bajos (en descarga y cadena de relampagos rondando los 1mil a 1500 y curaciones entre 10mil y crit 16mil)
Ahora que se ve que tenemos Poder con Hechizos sigue saliendo la misma cantidad en daño y en curacion, esta bug? 
Favor al staff ver eso, que ahora mismo solo dependemos del ataque melee siendo el chaman un guerrero a corta y larga distancia ademas de poder curarse con eficiencia

**Comment by elsharky** [comment]
PResura Mental: ahora tu poder con hechizos es igual a un 55% de tu poder de ataque y ya no te beneficias de otras fuentes de poder con hechizos. Tambien reduce un 75% el coste de mana de tus hechizos instanteneos beneficios, dañinos o de totem.

Bien... hace unos meses que el chaman mejora vuelve a estar sin ese poder y con el bajo daño y curacion que ahora tiene (siendo una clase melee y estar al centro de la pelea) pierde mucha supervivencia con ello y quisiera que por favor lo vean

Hace mas o menos un mes se arreglo 2 poderes de la clase chaman que estaban overbug
Cadena y descarga de relampagos de la rama elemental y Curaciones de la rama Restauracion: creo que solo bajaron los numeros ya que ahora va bien en sus respectivas ramas pero en Mejora se nerfeo completamente!

Siendo una habilidad principal ya que el chaman mejora se caracteriza por ser un melee que puede atacar a distancia y curarse pero anda recontra nerf ni para cosquillas xD

descarga y cadena de relampagos:
Hace un promedio de 800 a 1000 de daño

curaciones:
Ola de SAnacion superior (la mas fuerte) de 11mil con 3 segundos de casteo (7.5mil coste de mana)
ola de sanacion (la mediana) 6mil de curacion (pide poco 2mil de mana)
Ola de sanacion inferior (la menor) 8mil de curacion (pide 5mil de mana)
no vale la pena ni siquiera castearlo...

**Comment by GmTemis** [comment]
Por favor ponga algún elemento visual que sustente el error

**Comment by elsharky** [comment]
los hechizos lanzados con casi 8mil de poder con hechizos
http://subefotos.com/ver/?0afb52c077ea04b0fecce210f7750300o.jpg#codigos Cadena de relampagos 1356 de daño naturaleza con 2 segundos de casteo
http://subefotos.com/ver/?d9f165be4dbdb238ed95a50201e890bdo.jpg#codigos Choque de tierra 3744 de daño naturaleza instantaneo
http://subefotos.com/ver/?ea90f69f2aa262b3a5c9eee5a22d4a5bo.jpg#codigos descarga de relampagos 976 de daño naturaleza con 2.5 segundos de casteo
http://subefotos.com/ver/?2c905dec9b9b5256c2f45183c7efe8a4o.jpg#codigos Ola de sanacion Superior 11727 con 3 segundos de casteo y un tercio de uso de mana 

Espero sirva de algo este aporte para su trabajo y mejora de dichas habilidades

**Comment by rodrigoalv** [comment]
Hola, presura mental se ha reparado, faltaria ver si los daños de ciertos spell estan bajos para mirarlos. Cualquier cosa postearlos

**Comment by elsharky** [comment]
Pues los daños de todos los hechizos siguen igual y lo mismo con las curaciones... asi que porfavor revisar el arreglo que se implemento en realidad o habria que esperar a alguna caida del servidor para que pueda hacer efecto dicho arreglo? o.O

**Comment by rodrigoalv** [comment]
durante la tarde estara operativo, solo actualmente este en el test

**Comment by elsharky** [comment]
pues te cuento que ya paso dos tardes y aun no se ve ningun cambio, lo digo por reportar mas que por darte molestias y no pases a otras skills dejando esta nuevamente ahi, favor revisarlo

**Comment by rodrigoalv** [comment]
sharky, lo siento, me e entretenido en otras coas y no hemos puesto el fix en el servidor oficial (firelands) ahora cuando pongamos el fix para ultraxion, cuernonegro, batalla de gilneas  estara activo, en unas horas mas :D si estas online pon ticket y conversamos! Saludos

**Comment by elsharky** [comment]
ok

**Comment by elsharky** [comment]
ya merito? =/
digo... se implemento muchas cosas como el temple y algun arreglo de Guilneas... pero aun sigue bug Presura mental T_T
