### ISSUE TITLE
(hechizo), espiral de la muerte. caballero de la muerte

### ISSUE THREAD

**Issue by markhuz** [steelwow/Bugtracker-434#64]
esta habilidad puede ser usada para hacer daño y para sanar a un objetivo no-muerto
![wowscrnshot_010515_202028](https://cloud.githubusercontent.com/assets/9202321/5623338/3ae6fd02-9531-11e4-8164-d10b95ab33c1.jpg)
daño: 8252
sanacion: 28882
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

actualmente en el servidor:

daño: 23862
![wowscrnshot_010515_222013](https://cloud.githubusercontent.com/assets/9202321/5623374/c2132116-9531-11e4-90a4-2adeee184323.jpg)
sanacion: 33510
![wowscrnshot_010515_224141](https://cloud.githubusercontent.com/assets/9202321/5623390/0f6c426c-9532-11e4-8123-010e9528e755.jpg)

**Comment by rodrigoalv** [comment]
Se ha reparado

Saludos
