### ISSUE TITLE
[habilidad] Asolar (DK/Escarcha)

### ISSUE THREAD

**Issue by jjairojimenez** [steelwow/Bugtracker-434#65]
no esta realizando el daño que debe, y es la habilidad principal de los dk escarcha junto con el golpe de escarcha
![captura 4](https://cloud.githubusercontent.com/assets/10419912/5646145/b5571e80-9646-11e4-9065-dc1bfa45908c.png)
![captura 1](https://cloud.githubusercontent.com/assets/10419912/5646148/b55be30c-9646-11e4-99ef-d93afa9b140a.PNG)
![captura2](https://cloud.githubusercontent.com/assets/10419912/5646147/b5577b14-9646-11e4-8624-3a8a09bfe2ce.PNG)
![captura3](https://cloud.githubusercontent.com/assets/10419912/5646146/b557272c-9646-11e4-8ff6-463784c41608.PNG)

**Comment by GmTemis** [comment]
Por favor documente su reporte de lo contrario sera cerrado.

**Comment by jjairojimenez** [comment]
ya monte las imágenes, normalmente el asolar debe generar igual o mas daño que el golpe de escarcha el cual esta bien, pero el asolar no :(

**Comment by jjairojimenez** [comment]
ademas de todo, al golpear con asolar a un pj, este se come las enfermedades cosa que no debe ocurrir

**Comment by Ylonen** [comment]
Al golpear a un pj no es que no cuente las enfermedades, sino que al ser daño físico se ve reducido por la Armadura además del Temple.

**Comment by timh52280** [comment]
Si vais a poner solo que el daño esta mal así por que sí, la verdad este reporte no tiene sentido.

**Comment by zonicmc** [comment]
si la verdad es k al golpear un target con asolar k este enfermado se  consume las enfermedades tanto en pvp como en pve .
y ps obiamente va a bajar el dps
