### ISSUE TITLE
[Quest Bugg] Siguiendo Ordenes de Cuenca De Sholazar esta bugg

### ISSUE THREAD

**Issue by Kasins** [steelwow/Bugtracker-434#66]
En cuenca del sholazar en la faccion de corazon frenetico la quest que termina la cadena de misiones de la reputacion se encuentra buggeada. Pues te pide encontrar al oraculo herido y cuando lo encuentras matar a un cocodrilo, pues bien hasta ahi bien, cuando lo matas te completa la mision y la mision se debe entregar en el oraculo herido, como bien pone aqui: http://es.wowhead.com/quest=12540/siguiendo-ordenes
Pero no deja entregarla, no sale el signo de interrogacion caracteristico de cuando debes entregar una mision, y esta mision es muy importante pues con ella puedes hacer la reputacion de los oraculos.
Aqui dejo el link de un video de como se deberia hacer la mision sin que estuviese bugg: https://www.youtube.com/watch?v=QADPZvS2pxg. 
Sin embargo en nuestro server el hombre no aparece de pie si no mas a la izquierda tirado y aunque completes la quest no te deja entregarla y continuar la cadena de misiones.

**Comment by GmTemis** [comment]
Agrego este reporte cerrado para tener en cuenta. https://github.com/steelwow/Bugtracker-434/issues/67

**Comment by ghost** [comment]
https://github.com/steelwow/Bugtracker-434/issues/30 tambien estaba el mio antes... la gente ni se molesta en mirar y eso que hay pocos.
