### ISSUE TITLE
Problema Con Profesiones

### ISSUE THREAD

**Issue by peruzi123** [steelwow/Bugtracker-434#69]
Mi Herbolaria me aparece en 0 y la tengo full y mis  profesiones secundarias las tengo todas en 0 y no las puedo ver... ya tengo tiempo con el problema de igual manera ya había mandado ticket cuando aun era Dream-Wow y nada no me atendieron.... gracias :3
![wowscrnshot_010715_211703](https://cloud.githubusercontent.com/assets/8460973/5657312/bc3d67a6-96b2-11e4-9a3c-31ee2413bbac.jpg)
![wowscrnshot_010715_211721](https://cloud.githubusercontent.com/assets/8460973/5657322/e340f7b4-96b2-11e4-8ef5-3b98a0ed12c1.jpg)

**Comment by peruzi123** [comment]
Una disculpa por el titulo ni idea por que salio así..

**Comment by GmTemis** [comment]
Este sistema no es para solucionar errores individuales, por favor lee la normativa del bugtracker, para ello esta el foro o el sistema de tickets. Si quieres reportar un BUG general debes usar este medio.
