### ISSUE TITLE
Calculo de sanacion erroneo mania sangrienta

### ISSUE THREAD

**Issue by hermoso2009** [steelwow/Bugtracker-434#72]
Hola a todos, despues de probar varias veces este talento, y hacer los calculos, note que estan mal, aqui el caso que analice yo de este talento de warrior http://es.wowhead.com/spell=79561/mania-sangrienta, bien en cataclysmo este talento con 2 puntos tiene un 10% de probabilidad de sanar 4% de la vida durante 5 segundos al recibir daño, tiene dos errores, 
*primer ejemplo:
_Sujeto de prueba: warrior
_vida:                      171000
_curacion actual de mania sangrienta "5 tick de 1029 de sanacion"(1029x5= 5145)
_lo que deberia curar (4% de 171000 = 6840)
_la diferencia del error es 6840 - 5145 = 1695, eso es lo que le falta a la habilidad para estar bien.
*El segundo error es simplemente que como indica la descripcion, la habilidad tendria que tener la probabilidad de activarse frente al daño de todas las fuentes, en steelwow solo se esta activando al recibir daño exclusivo de jugadores, descartando elementales bestias y demas enemigos que nos enfrentamos al tanquear en una mazmorra.
_y quiero aclarar que esta prueba la hice teniendo este talento que lo mejora "Vendaje de batalla", que lo que hace es aumentar las autosanaciones un 20%, de modo que si "Vendaje de batalla" estaria bien en teoria, solo estaria mal la formula de calculo de sanacion de "Mania sangrienta", pero si arreglan la formula y Mania sangrienta cura lo que deberia, pero no aumenta la sanacion aun teniendo el talento "vendaje de batalla", entonces quiere decir que ese talento no aumenta la autosanacion del guerrero, por lo que por conclusion estaria bug.
_conclusion teniendo teniendo 2 puntos en "Mania sangrienta" y 2 en "Vendaje de batalla" lo que deberia curar es :  
_4% de 171000 = 6840 de Mania sangrienta, + el 20% de "Vendaje de batalla" (20% de 6840= 1368)
_En total deberia curar 8208 en 5 segundos, eso es todo mi aporte y espero que sirva para poner a tope al server, un saludo.

**Comment by rodrigoalv** [comment]
Se ha reparado vendaje de batalla, cuando este activo, por favor probarlo
