### ISSUE TITLE
error calculo sanacion Segundo aliento

### ISSUE THREAD

**Issue by hermoso2009** [steelwow/Bugtracker-434#73]
Hola a buenas he estado haciendo pruebas y encontre un mal calculo en este talento de guerrero http://es.wowhead.com/spell=29838/segundo-aliento , en cataclysmo este talento cura con "un punto" un 2% de la salud al recibir un ataque de tipo stun o inmobilizador durante 10 segundos y con 2 puntos cura 6%.

_Sujeto de prueba: guerrero
_vida:                      154000
_sanacion actual al recibir un daño de tipo inmobilizador " 5 tick de 327 = 1635"
_sanacion que deberia hacer: el 2% de 154000 =es "3080"
_para que la habilidad este arreglada deberia curar (3080 - 1635 = 1445) "1445" mas.
_y quiero aclarar que esta prueba la hice teniendo este talento que lo mejora "Vendaje de batalla", que lo que hace es aumentar las autosanaciones un 20%, de modo que si "Vendaje de batalla" estuviera bien en teoria, solo estaria mal la formula de calculo de sanacion de "Segundo aliento", pero si arreglan la formula y "Segundo aliento" cura lo que deberia, pero no aumenta la sanacion aun teniendo el talento "vendaje de batalla" que lo mejora, entonces quiere decir  por conclusion estaria bug.
_conclusion teniendo 2 puntos en el talento de "Segundo Aliento" y 2 en "Vendaje de batalla" lo que deberia curar es : 
el 6% de 154000 es 9240, mas el 20% de "vendaje de batalla (20% de 9240= 1848)"
_Para que la habilidad este arreglada deberia curar 9240(Segundo aliento) + 1848 (Vendaje de batalla) =              11088 en 10 segundos ( 5 tick de 2217 ), este es mi aporte para mejorar el server y que cada dia haya menos bugs, un saludo.

**Comment by rodrigoalv** [comment]
se ha reparado vendaje de batalla, por favor cuando este activo, probar
