### ISSUE TITLE
NPC jamusvaz le hacen falta items en su inventario.

### ISSUE THREAD

**Issue by Edriel** [steelwow/Bugtracker-434#74]
Buenas.
Reporto que el npc jamusvaz (http://www.wowhead.com/npc=46556/jamusvaz) vendedor de items por puntos de valor, le hacen faltan items en su inventario, son 3 armas arrojadizas que en listare a continuación:
1.-  Darting Chakram (http://www.wowhead.com/item=77087).
2.- Unexpected Backup (http://www.wowhead.com/item=77085).
3.- Windslicer Boomerang (http://www.wowhead.com/item=77086).

Cabe mencionar que en wowhead ya no marca que estas armas arrojadizas sean del inventario del npc ya en mención debido a que se han actualizado las bases de datos de wowhead; en este caso se removieron los items; pero en su momento los tubo así que por favor de agregarlos ya que ayudarían a las clases en relación a estas armas. 
De antemano gracias.

**Comment by rodrigoalv** [comment]
se han agregado a los vendedores de la alianza y la horda

**Comment by Edriel** [comment]
Re abro tema solo para decirles que los costos de estas armas son 700 puntos de valor en wowhead ya no trae el precio, pero no se si valga la información que trae el addon atlasloot, cabe mencionar que el mismo addon indica los precios de muchos otros items y coinciden en los precios.
Anexo imagen desde in-game con el addon atlasloot.
http://www.subeimagenes.com/img/wowscrnshot-011315-203347-1201655.html
