### ISSUE TITLE
[Spells] Buffs con mismos efectos

### ISSUE THREAD

**Issue by Ylonen** [steelwow/Bugtracker-434#77]
Ya que todos denuncian pero nadie reporta

http://es.wowhead.com/spell=19740 - Bendición de poderío - no comparte efecto con otro buff

http://es.wowhead.com/spell=20217 - Bendición de reyes - comparte efecto con Marca de lo salvaje, Bendición de los reyes olvidados (peletería), y Abrazo de la araña de esquisto

http://es.wowhead.com/spell=1126   -  Marca de lo salvaje - comparte efecto con Bendición de reyes, bendición de los reyes olvidados (peletería) y Abrazo de la araña de esquisto

http://es.wowhead.com/spell=90363 - Abrazo de la araña de esquisto - comparte efecto con Bendición de reyes, Marca de lo salvaje y Bendición de los reyes olvidados (peletería)

http://es.wowhead.com/spell=69378 - Bendición de los reyes olvidados (Peletería) - comparte efecto con Bendición de reyes, Marca de lo salvaje y Abrazo de la araña de esquisto

http://es.wowhead.com/spell=6673   - Grito de batalla - comparte efecto con Cuerno de Invierno

http://es.wowhead.com/spell=57330  - Cuerno de Invierno - comparte efecto con Grito de batalla

http://es.wowhead.com/spell=21562   - Palabra de poder: Entereza - Comparte efecto con Entereza, Grito de orden y Pacto de sangre

http://es.wowhead.com/spell=111922 - Entereza - comparte efecto con Grito de orden, Pacto de sangre, Palabra de poder: Entereza

http://es.wowhead.com/spell=469      - Grito de Orden - comparte efecto con Palabra de poder: Entereza, Entereza y Pacto de sangre.

http://es.wowhead.com/spell=166928  - Pacto de sangre - comparte efecto con Palabra de poder: Entereza, Entereza y Grito de Orden

Si Bendición de Poderío comparte efecto con otro buff contribuir con el reporte

**Comment by rodrigoalv** [comment]
cuando este en el changelog probarlo
