### ISSUE TITLE
[Talento] Golpes despiadados (Pícaro/Sutileza)

### ISSUE THREAD

**Issue by sergioadivina** [steelwow/Bugtracker-434#79]
Esta habilidad debería devolverte 25p de energía con cualquier remate (habilidad que requiere puntos de combo) siempre que cumplas los requisitos y con reponerse no se activa.

**Comment by rodrigoalv** [comment]
hola:

se ha reparado, cuando este en el bugtracker estara disponible

**Comment by rodrigoalv** [comment]
changelog*\* no bugtracker erro xD
