### ISSUE TITLE
Buff Druida de las llamas para los ferales

### ISSUE THREAD

**Issue by Felcius** [steelwow/Bugtracker-434#85]
Porfavor fixeen el buff druida de las llamas http://www.wowhead.com/spell=99244/druid-of-the-flames
del baston http://es.wowhead.com/item=71466/guadana-llameante-de-fandral, hace tiempo que tengo el baston y todavia no fixean su uso.

Un Saludo

**Comment by rodrigoalv** [comment]
hola:

Cuando este en el changelog estara disponible! 

Saludos
