### ISSUE TITLE
[Abalorio] Nido del ultimo dragon

### ISSUE THREAD

**Issue by sergioadivina** [steelwow/Bugtracker-434#88]
Se activa continuamente osea que no tiene cd interno por lo tanto esta bastante over. Esto pasaba también con los otros abalorios de ds antiguamente hasta que se repararon tambien así que recomiendo antes de poner nuevos bosses mirar los abalorios que tiraran esos nuevos bosses.
Link del abalorio: http://es.wowhead.com/item=77205/nido-del-ultimo-dragon

**Comment by GmTemis** [comment]
Reparado
