### ISSUE TITLE
BUG en Reparacion Stack de Buffs

### ISSUE THREAD

**Issue by elsharky** [steelwow/Bugtracker-434#89]
Cambios Generales
 Spell buff / auras, ya no podran ser bufeadas por 2 jugadores diferentes a un mismo jugador (ejemplo: 2 bendiciones de reyes)

Eso fue lo que se implemento en el changelog para el juego... pero ocaciono que la pasiva de chaman mejora y en algunos cazos del cazador que da un buff de 20% de poder de ataque se pierda al ser buffeado por un paladin con poderio que absorve la pasiva y si el personaje muere o es limpiado el poderio pierde la pasiva y no vuelve a aparecer hasta reloguear, comprenderan que es perjudicial ello a la hora de jugar en BG's

**Comment by Ylonen** [comment]
Por cierto no quedo del todo bien, pues si hay dos palas en grupo (sea grupo. banda o bg) y uno tira una bendición, la bendición del otro pala, aun siendo la contraría, se sobrepone a la que ya estaba (sobre los pasivos de chaman y caza no me había fijado)

**Comment by rodrigoalv** [comment]
Lo del cazador esta reparado
