### ISSUE TITLE
Reinicio de Puntos de Valor

### ISSUE THREAD

**Issue by Ylonen** [steelwow/Bugtracker-434#92]
Ya van varias semanas de que al reiniciar los IDs semanales, no se reinicia el máximo semanal de  puntos de valor... haciendo así que pases toda otra semana sin poder ganar puntos.

<a href="http://subefotos.com/ver/?ce7fdae6f14c265e3f89fd76c7ae9bffo.jpg" target="_blank"> <img src="http://thumbs.subefotos.com/ce7fdae6f14c265e3f89fd76c7ae9bffo.jpg" /></a>

(click a la miniatura para verla a tamaño completo)

PD: Respecto a esto me dijeron por /taberna que pusiera un ticket... sin embargo olvide hacer esto y me fui a DS10n con mi Sacer (ignorando que el ya estaba en los 1000/1000), logrando así no ganar absolutamente ni un punto de los bosses que matamos (Morchok*, Señor de la Guerra Zon'ozz , Yor'sahj el Velador, y Hagara la Vinculatormentas) c:

**Comment by GmTemis** [comment]
No se resuelven problemas individuales en el bugtracker. Cierro

**Comment by Ylonen** [comment]
Ahora que lo veo un mes despues... no se a que te refieres con problemas individuales... en ningun lado leo "denme los puntos que no gane" y estoy seguro que no solo me pasa eso a mi y ademas... ¿es mi culpa que no se me reinicien los puntos? Esto comenzo a ocurrir cuando hicieron un fix hace tiempo.. asi que culpa de quien sera?
