### ISSUE TITLE
Habilidad reponerse picaro

### ISSUE THREAD

**Issue by Jualk** [steelwow/Bugtracker-434#99]
Buenas noches como dice el titulo esta habilidad anda bugg ya que al tener 5 puntos de combos esta otorgando 75 de energia, lo que da una enorme ventaja a esta clase ya que se pueden hacer enboscadas ilimitadas mientras dure danza de las sombras por ejemplo en la rama sutiliza adj imagen.

http://subefotos.com/ver/?64fea4f78b1c4205a828278fcb9d4d84o.jpg#codigos

Saludos

**Comment by rodrigoalv** [comment]
reparado.

Fue un error, estaba tomando los 3 rangos del spell (golpes despiadados 1/3, 2/3, 3/3) se ha reparado, y ahora solo da 25 puntos de energia.

Por otro lado, estoy viendo el spell que te otorga energia para ver si debe o no sacar de sigilo.

Saludos (dejo el ticket cerrado por su reparacion, al reiniciar el servidor estara disponible)

**Comment by rodrigoalv** [comment]
Segun mis conocimientos, y preguntas a jugadores, no deberia sacar de sigilo (esto tambien esta reparado) y esta disponble al reinicio del servidor
